language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aababei/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aababei/docker-react npm run test